import type { KnowledgeDraft, KnowledgeSelection, KnowledgeView } from './project-knowledge.js';
const e = (s:unknown) => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const fields = (data:Record<string,unknown>) => Object.entries(data).map(([k,v])=>`<input type="hidden" name="${e(k)}" value="${e(v)}">`).join('');
export const KNOWLEDGE_CSS = `.knowledge{max-width:780px;min-width:0;overflow-wrap:anywhere}.knowledge .card{padding:20px;min-width:0;margin:16px 0}.knowledge h2{margin:0 0 12px}.knowledge form{display:grid;gap:12px;margin:0}.knowledge label{display:grid;gap:6px}.knowledge textarea,.knowledge input,.knowledge select{box-sizing:border-box;width:100%;min-width:0;max-width:100%}.knowledge textarea{resize:vertical;min-height:110px}.knowledge button,.knowledge summary,.knowledge .button-link{min-height:44px}.knowledge button{justify-self:start;white-space:nowrap}.knowledge summary{padding:12px 0;cursor:pointer}.knowledge pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}.knowledge .knowledge-actions{display:flex;gap:12px;flex-wrap:wrap}.knowledge .meta{font-size:.86rem}.knowledge .knowledge-source{display:block}.knowledge details+details{border-top:1px solid var(--line,#ddd)}@media(max-width:600px){.knowledge .card{padding:16px}.knowledge h2{font-size:1.1rem}}`;
export function knowledgeHtml(view:KnowledgeView,csrf:string,canManage:boolean,draft?:KnowledgeDraft,error?:string):string {
  const manage=canManage && !!csrf;
  const base={csrf,repo:view.repo,identity:view.identity,revision:view.revision};
  const form=(action:string,body:string,extra:Record<string,unknown>={})=>`<form method="post" action="/settings/knowledge/change">${fields({...base,action,...extra})}${body}</form>`;
  const referenceFields=(d:KnowledgeDraft)=>`<label>Name<input name="title" maxlength="120" value="${e(d.title)}" required></label><label>Reference text<textarea name="content" rows="5" maxlength="12000">${e(d.content)}</textarea></label><details${d.path?' open':''}><summary>Use a project document</summary><label>Committed .md or .txt path<input name="path" value="${e(d.path)}" placeholder="docs/design-guide.md"></label><p class="meta">Uses the committed file instead of the text above. Save again to refresh it.</p></details><button type="submit">Save reference</button>`;
  const refs=view.knowledge.references.map(ref=>`<details class="card"${draft?.id===ref.id?' open':''}><summary><strong>${e(ref.title)}</strong></summary>${ref.path?`<span class="meta knowledge-source">${e(ref.path)} · ${e(ref.sourceRevision?.slice(0,7))}</span>`:''}<pre>${e(ref.content)}</pre>${manage?`<details${draft?.id===ref.id?' open':''}><summary>Edit reference</summary>${form('save',referenceFields(draft?.id===ref.id?draft:{title:ref.title,content:ref.path?'':ref.content,path:ref.path??''}),{id:ref.id})}<details><summary>Remove reference</summary>${form('remove','<p>Remove from future tasks. Previous run context stays available.</p><button>Remove reference</button>',{id:ref.id})}</details></details>`:''}</details>`).join('');
  const history=view.history.map(h=>`<li><a class="button-link" href="/settings/knowledge?repo=${encodeURIComponent(view.repo)}&version=${h.revision}">Version ${h.revision}</a> · ${e(h.actor)} · ${e(h.at.slice(0,16).replace('T',' '))} UTC</li>`).join('');
  return `<section class="knowledge">${error?`<p class="problem" role="alert">${e(error)}</p>`:''}<section class="card"><h2>Instructions</h2>${manage?form('instructions',`<textarea aria-label="Project instructions" name="instructions" rows="5" maxlength="4000" placeholder="Goals, preferences, and what good work looks like…">${e(draft?.instructions??view.knowledge.instructions)}</textarea><button>Save instructions</button>`):`<pre>${e(view.knowledge.instructions||'No project instructions yet.')}</pre>`}</section><section><h2>References</h2>${refs||'<p class="meta">Add a spec, design guide, or useful project document.</p>'}${manage?`<details class="card"${draft?.title&&!draft.id?' open':''}><summary>Add reference</summary>${form('save',referenceFields(draft?.id?{}:draft??{}))}</details>`:''}</section>${history?`<details><summary>Change history</summary><ol>${history}</ol></details>`:''}</section>`;
}
export function knowledgeContextHtml(snapshot:KnowledgeSelection|null):string {
  if (!snapshot) return '';
  return `<details class="knowledge result-knowledge"><summary>Context used</summary><p class="meta">Project knowledge · version ${snapshot.revision}${snapshot.inheritedFrom===null?'':` · from run #${snapshot.inheritedFrom}`}</p>${snapshot.instructions?`<details><summary>Instructions</summary><pre>${e(snapshot.instructions)}</pre></details>`:'<p>No project instructions were supplied.</p>'}${snapshot.references.map(r=>`<details><summary>${e(r.title)}</summary>${r.path?`<p class="meta">${e(r.path)} · ${e(r.sourceRevision)}</p>`:''}<pre>${e(r.content)}</pre></details>`).join('')}${snapshot.omitted.length?`<details><summary>Not included (${snapshot.omitted.length})</summary><ul>${snapshot.omitted.map(r=>`<li>${e(r.title)} — ${e(r.reason)}</li>`).join('')}</ul></details>`:''}</details>`;
}
