/**
 * Putting the command on PATH, as an explicit act.
 *
 * Standing Orders refuses to install things on an operator's behalf — it prints
 * the command and its side effects and lets them run it. A tool that applied
 * that rule to `bd init` and then quietly edited PATH during its own install
 * would not deserve to be believed, so this is a command you run, it shows
 * you what it will do before it does it, and `unlink` undoes it exactly.
 *
 * Three rules hold throughout: never sudo, never a directory outside the home
 * directory unless explicitly named, and never delete anything that is not
 * something we put there.
 *
 * Two mechanisms, because "a command on PATH" means different things. On POSIX
 * it is a symlink with the execute bit set. On Windows the shell resolves
 * commands through PATHEXT, so an extensionless symlink is invisible no matter
 * which directory it sits in — there it is a `.cmd` shim, which is also what
 * npm writes, and which needs no Developer Mode to create.
 */

import { chmod, mkdir, lstat, readFile, readlink, stat, symlink, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";

const isWindows = process.platform === "win32";

/** What you type. */
export const BIN_NAME = "standing-orders";

/** What lands on disk. Windows needs the extension to resolve it through PATHEXT. */
export const LINK_FILE = isWindows ? `${BIN_NAME}.cmd` : BIN_NAME;

/** Owner, group, and other execute — the same bits npm sets on a package bin. */
const EXECUTABLE_BITS = 0o111;

/**
 * How a shim is known to be ours. The symlink case can ask the filesystem what
 * it is; a `.cmd` is an ordinary file, so it has to say so in its own text or
 * `unlink` could not tell it from someone else's program of the same name.
 */
const SHIM_MARKER = "standing-orders-link: generated by `standing-orders link`";

export type TargetChoice = { dir: string; onPath: boolean };

export type LinkPlan =
  | { action: "create"; source: string; target: string }
  | { action: "already"; source: string; target: string }
  | { action: "replace"; source: string; target: string; current: string }
  | { action: "conflict"; source: string; target: string; reason: string };

export type UnlinkPlan =
  | { action: "remove"; target: string; current: string }
  | { action: "absent"; target: string }
  | { action: "foreign"; target: string; reason: string };

/**
 * Windows path comparison is case-insensitive, and a PATH entry may or may not
 * carry a trailing separator. Comparing the raw strings means a directory that
 * is on PATH gets reported as missing from it.
 */
function comparablePath(path: string): string {
  const trimmed = path.length > 1 && path.endsWith(sep) ? path.slice(0, -1) : path;
  return isWindows ? trimmed.toLowerCase() : trimmed;
}

function samePath(left: string, right: string): boolean {
  return comparablePath(left) === comparablePath(right);
}

/** Whether `path` is the home directory or sits beneath it. */
function isInside(path: string, home: string): boolean {
  const inner = comparablePath(path);
  const outer = comparablePath(home);
  return inner === outer || inner.startsWith(outer + sep);
}

/**
 * Where the link should go. Only directories inside the home directory are
 * ever proposed: everything else needs sudo, and needing sudo to read your own
 * git repositories would be absurd.
 */
export function chooseTarget(options: {
  pathEntries: readonly string[];
  home: string;
  override?: string;
}): TargetChoice {
  const { pathEntries, home, override } = options;
  const isOnPath = (dir: string) => pathEntries.some(entry => samePath(entry, dir));

  if (override !== undefined) {
    const dir = resolve(override);
    return { dir, onPath: isOnPath(dir) };
  }

  const conventional = [join(home, ".local", "bin"), join(home, "bin")];
  const preferred = conventional.find(isOnPath);
  if (preferred !== undefined) return { dir: preferred, onPath: true };

  const homeOwned = pathEntries.find(entry => isInside(entry, home));
  if (homeOwned !== undefined) return { dir: homeOwned, onPath: true };

  // Nothing usable on PATH. Propose the conventional location and say so.
  return { dir: conventional[0] as string, onPath: false };
}

export async function planLink(source: string, dir: string): Promise<LinkPlan> {
  const target = join(dir, LINK_FILE);
  const existing = await describeExisting(target);

  if (existing === null) return { action: "create", source, target };
  if (existing.kind === "foreign") {
    return { action: "conflict", source, target, reason: existing.reason };
  }
  if (samePath(existing.pointsTo, source)) return { action: "already", source, target };
  return { action: "replace", source, target, current: existing.pointsTo };
}

export async function applyLink(plan: LinkPlan): Promise<void> {
  if (plan.action === "conflict") {
    throw new Error(`${plan.target}: ${plan.reason} — remove it yourself if you want it gone`);
  }
  if (plan.action === "already") return;

  await mkdir(dirname(plan.target), { recursive: true });
  // Only ever removing a shim we recognise, never someone else's file.
  if (plan.action === "replace") await unlink(plan.target);

  if (isWindows) {
    await writeFile(plan.target, shimText(plan.source));
    return;
  }
  await symlink(plan.source, plan.target);
  await ensureExecutable(plan.source);
}

/**
 * `%*` forwards arguments with their quoting intact — the same mechanism npm's
 * own generated shims use — and `EXIT /B` hands the command's exit code back to
 * the shell, without which a failing scan would look like a success to anything
 * that checked.
 *
 * The path is written with `%` doubled, because a percent sign is legal in a
 * Windows path and cmd would otherwise read `%Foo%` in it as a variable and
 * substitute it away. The `REM source:` line keeps the path verbatim: it is
 * read back by this program, not by cmd.
 *
 * `SETLOCAL DisableDelayedExpansion` is not ceremony. Delayed expansion is
 * inherited — a shim invoked under `cmd /v:on`, or from a batch file that
 * enabled it, would have every `!` in the path *and in the arguments* eaten
 * before node saw them, turning `a!name!b` into `ab` silently. Disabling it for
 * our own scope is the only way to be sure. `ENDLOCAL &` shares a line with the
 * exit so that `%ERRORLEVEL%` is read inside the scope, before it is torn down.
 *
 * One inherited quirk remains, worth knowing before someone reports it as a
 * bug: a batch file reaching this through CALL has its arguments parsed a
 * second time by cmd, which doubles any caret in them. That happens to
 * `CALL node ...` just the same, with no shim involved, and no batch file can
 * avoid it — only a compiled launcher could. The tests pin the shim to being
 * transparent rather than to being immune.
 */
function shimText(source: string): string {
  return [
    "@ECHO off",
    `REM ${SHIM_MARKER}; safe to delete`,
    `REM source: ${source}`,
    "SETLOCAL DisableDelayedExpansion",
    `node "${source.replaceAll("%", "%%")}" %*`,
    "ENDLOCAL & EXIT /B %ERRORLEVEL%",
    "",
  ].join("\r\n");
}

/** The source a shim points at, or null when the text is not one of ours. */
function readShimSource(text: string): string | null {
  if (!text.includes(SHIM_MARKER)) return null;
  const declared = /^REM source: (.+)$/m.exec(text);
  return declared?.[1]?.trim() ?? null;
}

/**
 * tsc emits a file with the shebang intact but without the execute bit, so a
 * symlink to it fails with "permission denied" the first time it is typed.
 * Windows has no such bit, and chmod there is a no-op at best.
 */
async function ensureExecutable(source: string): Promise<void> {
  if (isWindows) return;
  const stats = await stat(source);
  const wanted = stats.mode | EXECUTABLE_BITS;
  if (wanted !== stats.mode) await chmod(source, wanted);
}

export async function planUnlink(dir: string): Promise<UnlinkPlan> {
  const target = join(dir, LINK_FILE);
  const existing = await describeExisting(target);

  if (existing === null) return { action: "absent", target };
  if (existing.kind === "foreign") {
    return { action: "foreign", target, reason: existing.reason };
  }
  return { action: "remove", target, current: existing.pointsTo };
}

export async function applyUnlink(plan: UnlinkPlan): Promise<void> {
  if (plan.action === "foreign") {
    throw new Error(`${plan.target}: ${plan.reason} — leaving it alone`);
  }
  if (plan.action === "absent") return;
  await unlink(plan.target);
}

type Existing = { kind: "ours"; pointsTo: string } | { kind: "foreign"; reason: string };

/**
 * null when nothing is there. Otherwise: ours, and what it points at, or
 * foreign, and why we will not touch it.
 */
async function describeExisting(target: string): Promise<Existing | null> {
  let stats;
  try {
    stats = await lstat(target);
  } catch {
    return null;
  }

  if (isWindows) {
    if (!stats.isFile()) {
      return { kind: "foreign", reason: "something that is not a file is already there" };
    }
    let text: string;
    try {
      text = await readFile(target, "utf8");
    } catch {
      return { kind: "foreign", reason: "something unreadable is already there" };
    }
    const pointsTo = readShimSource(text);
    if (pointsTo === null) {
      return { kind: "foreign", reason: "a program we did not write is already there" };
    }
    return { kind: "ours", pointsTo };
  }

  if (!stats.isSymbolicLink()) {
    return { kind: "foreign", reason: "something that is not a link is already there" };
  }
  // readlink returns the link's raw text, which may be relative. Comparing that
  // against an absolute source would call a perfectly good link stale and
  // replace it on every run.
  const raw = await readlink(target);
  return { kind: "ours", pointsTo: resolve(dirname(target), raw) };
}
