import { afterEach, expect, test } from 'vitest';
import { mkdtempSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { openStore, type Store } from './store.js';
import { addApprover } from './scope.js';
import { mintCoordinator, revokeCoordinator } from './coordinator.js';
import { applyProjectProfile, projectProfilePath, readProjectProfile, runProjectCommand } from './project-cli.js';

let dir: string, store: Store;
afterEach(() => { store?.close(); if (dir) rmSync(dir, { recursive: true, force: true }); });
test('project selection records exact saved paths and only a credential reference, with fresh scoped authentication', async () => {
  dir = realpathSync(mkdtempSync(join(tmpdir(), 'so-project-cli-')));
  const databaseFile = join(dir, 'orders.db'); store = openStore(databaseFile);
  const first = join(dir, 'first'), second = join(dir, 'second'); mkdirSync(first); mkdirSync(second);
  const registryFile = join(dir, 'repos.json'); writeFileSync(registryFile, JSON.stringify({ version: 2, repos: [first, second], roots: [] }));
  const now = new Date(); addApprover(store, 'operator', now);
  const minted = mintCoordinator(store, { name: 'lead', repos: [first], by: 'operator', now });
  if (!minted.ok) throw Error('coordinator fixture');
  const tokenFile = join(dir, 'lead-token'); writeFileSync(tokenFile, minted.token);
  let line = '';
  const context = { store, databaseFile, registryFile, json: true, write: (value: string) => { line = value; } };
  const selected = await runProjectCommand(['use', first], new Map([['token-file', tokenFile]]), context);
  expect(selected, line).toBe(0);
  expect(JSON.parse(line)).toMatchObject({ ok: true, command: 'project use', result: { profile: { repo: first, tokenFile } } });
  expect(readFileSync(projectProfilePath(databaseFile), 'utf8')).not.toContain(minted.token);
  const flags = new Map<string, string | true>(); applyProjectProfile('knowledge', ['search', 'thing'], flags, databaseFile);
  expect(Object.fromEntries(flags)).toEqual({ repo: first, 'token-file': tokenFile });
  const operator = new Map<string, string | true>([['as', 'operator']]); applyProjectProfile('task', ['complete', 'one'], operator, databaseFile);
  expect(operator.has('token-file')).toBe(false);
  expect(await runProjectCommand(['use', second], new Map([['token-file', tokenFile]]), context)).toBe(3);
  expect(readProjectProfile(databaseFile)?.repo).toBe(first);
  expect(await runProjectCommand(['use', join(dir, 'unknown')], new Map(), context)).toBe(3);
  revokeCoordinator(store, minted.cid, 'operator', now);
  expect(await runProjectCommand(['use', first], new Map([['token-file', tokenFile]]), context)).toBe(3);
  expect(JSON.parse(line)).toMatchObject({ reason: 'unauthenticated' });
  expect(await runProjectCommand(['use', second], new Map(), context)).toBe(0);
  expect(readProjectProfile(databaseFile)).toEqual({ version: 1, repo: second, tokenFile: null });
});
