import type { RepositoryContext } from './repository-context.js';
const escape = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
export function repositoryContextHtml(repo: string, query: string, result: RepositoryContext | null, csrf: string): string {
  const root = `/settings/knowledge?repo=${encodeURIComponent(repo)}`;
  return `<section class="knowledge repository-context"><h2>Relevant code</h2><form method="get" action="/settings/knowledge"><input type="hidden" name="repo" value="${escape(repo)}"><label>Find code<input name="q" value="${escape(query)}" maxlength="1000" placeholder="A feature, file or symbol"></label><button type="submit">Search</button></form>` +
    (result === null ? '' : `<p class="meta">${result.index.engine === 'typescript-ast' ? 'Code relationships' : 'Source search'}${result.mode === 'impact' ? ' · possible change impact' : ''}</p>` +
      (result.excerpts.length ? result.excerpts.map(one => `<details><summary>${escape(one.file)}:${one.line}${one.symbol ? ` · ${escape(one.symbol)}` : ''}</summary><p class="meta">${escape(one.reason)}</p><pre>${escape(one.text)}</pre><a href="${root}&mode=impact&q=${encodeURIComponent(one.file)}">What this may affect</a></details>`).join('') : '<p>No matching source was found in this bounded search.</p>') +
      (result.relationships.length ? `<details><summary>Related files</summary><ul>${result.relationships.map(one => `<li>${escape(one.from)} → ${escape(one.to)} · ${escape(one.kind)}</li>`).join('')}</ul></details>` : '') +
      `<details><summary>Context details</summary><p>${escape(result.index.status)}${result.checkout ? ` · checkout ${escape(result.checkout.head.slice(0, 8))}` : ''}</p>${result.warnings.map(one => `<p>${escape(one)}</p>`).join('')}</details>`) +
    (csrf ? `<details><summary>Refresh code index</summary><form method="post" action="/settings/knowledge/refresh"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="repo" value="${escape(repo)}"><p>Builds a local map of TypeScript and JavaScript imports. Uses no model.</p><button type="submit">Refresh index</button></form></details>` : '') + `</section>`;
}
