import { afterEach, describe, expect, test } from 'vitest';
import { mkdtempSync, realpathSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { Server } from 'node:http';
import { openStore, type Store } from './store.js';
import { addApprover, hashPassword } from './scope.js';
import { ceilingDigestOf } from './principal.js';
import { createDecisionServer } from './serve.js';
let server: Server | undefined, store: Store | undefined, directory: string | undefined;
afterEach(async () => { if (server) await new Promise<void>((resolve, reject) => server!.close(error => error ? reject(error) : resolve())); server = undefined; store?.close(); store = undefined; if (directory) rmSync(directory, { recursive: true, force: true }); });
describe('shared team server binding', () => {
  test('cookie CSRF, origin and bearer share the same saved conversation and preserve private chat', async () => {
    directory = realpathSync(mkdtempSync(join(tmpdir(), 'standing-team-http-')));
    store = openStore(':memory:');
    const account = addApprover(store, 'alex', new Date()); if (!account.ok) throw Error('account');
    server = createDecisionServer({ store, evidenceRoot: directory, repos: [directory] });
    await new Promise<void>(resolve => server!.listen(0, '127.0.0.1', resolve));
    const address = server.address(); if (!address || typeof address === 'string') throw Error('no address');
    const base = `http://127.0.0.1:${address.port}`;
    const login = await fetch(base + '/login', { method: 'POST', body: new URLSearchParams({ name: 'alex', token: account.token }), redirect: 'manual' });
    const cookie = login.headers.get('set-cookie')!.split(';')[0]!;
    const initial = await (await fetch(base + '/chat?team=1&format=workspace', { headers: { cookie } })).json();
    expect(initial.team.canCreateLead).toBe(true);
    const post = (args: unknown, extra: Record<string, string> = {}) => fetch(base + '/api/team', { method: 'POST', headers: { cookie, 'content-type': 'application/json', ...extra }, body: JSON.stringify(args) });
    const input = { operation: 'create-lead', args: { name: 'Team lead', projects: [directory] } };
    expect((await post(input)).status).toBe(403);
    expect((await post(input, { 'x-csrf-token': initial.csrf, origin: 'https://not-our-console.example' })).status).toBe(403);
    const made = await (await post(input, { 'x-csrf-token': initial.csrf })).json();
    expect(made.ok).toBe(true);
    const room = await (await post({ operation: 'create-conversation', args: { leadId: made.result.leadId, title: 'Settings page', visibility: 'team', projects: [directory] } }, { 'x-csrf-token': initial.csrf })).json();
    expect(room.ok).toBe(true);
    const api = await (await fetch(base + '/api/team?conversation=' + room.result.conversationId, { headers: { authorization: `Bearer alex:${account.token}` } })).json();
    expect(api.snapshot.selected.title).toBe('Settings page');
    const page = await (await fetch(base + '/chat?format=workspace', { headers: { cookie } })).json();
    expect(page.team.selected.id).toBe(room.result.conversationId); expect(page.conversation).toBe(null);
    const privatePage = await (await fetch(base + '/chat?private=1&format=workspace', { headers: { cookie } })).json();
    expect(privatePage.team).toBeUndefined();
    // A second participant reviews the saved terms through the same native
    // proposal door. The original author remains attached to the turn.
    const now = new Date();
    store.saveApprover('sam', hashPassword('fixture-sam'), now);
    store.setAccountProjects('sam', [directory], 'alex', now);
    store.setChatConfig({ provider: 'codex-subscription', model: 'default', dailyTurns: 50, weeklyCeilingMicrousd: 0, priceInMicrousd: 0, priceOutMicrousd: 0 }, 'alex', now);
    const state = room.snapshot;
    const added = await (await post({ operation: 'member', args: { conversationId: room.result.conversationId, account: 'sam', role: 'contributor', active: true, expectedRevision: state.selected.revision, joinLead: true, expectedLeadRevision: state.leads.find((lead: {id:string}) => lead.id === made.result.leadId).revision } }, { 'x-csrf-token': initial.csrf })).json();
    expect(added.ok).toBe(true);
    const task = store.createTask({ id: 'shared-task', title: 'Settings page' }, now);
    store.placeTask(store.lookupRef('shared-task')!.id, directory);
    const focused = await fetch(base + '/chat?task=shared-task&conversation=' + state.selected.id + '&format=workspace', { headers: { cookie } });
    expect(focused.status).toBe(200);
    expect((await focused.json()).team.selected.id).toBe(state.selected.id);
    const digest = ceilingDigestOf([directory]);
    const session = store.mintTeamMateSession({ approver: 'alex', approverGeneration: store.accountOf('alex')!.generation, thread: state.selected.threadId, credentialKey: 'fixture-key', ceilingMicrousd: 1_000_000, ceilingDigest: digest, termsDigest: 'fixture-terms' }, now);
    const opened = store.openMateTurn({ approver: 'alex', session, thread: state.selected.threadId, credentialKey: 'fixture-key', reservedMicrousd: 10, dailyTurns: 50, weeklyCeilingMicrousd: 5_000_000, deadlineMs: 60_000 }, now);
    if (!opened.ok) throw Error(opened.reason);
    const started = store.startMateTurn(opened.id, now); if (!started.ok) throw Error('start');
    const proposal = store.draftMateProposal({ thread: state.selected.threadId, turn: opened.id, kind: 'hold', payload: { task: 'shared-task', reason: 'Wait for the settings copy decision.', sawHold: null }, ceilingDigest: digest }, now);
    const nativeOnly = store.draftMateProposal({ thread: state.selected.threadId, turn: opened.id, kind: 'cancel', payload: { task: 'shared-task' }, ceilingDigest: digest }, now);
    store.finalizeMateTurn(opened.id, started.generation, { state: 'answered', settledMicrousd: 1, tokensIn: 1, tokensOut: 1 }, now);
    store.mintTeamMateSession({ approver: 'sam', approverGeneration: store.accountOf('sam')!.generation, thread: state.selected.threadId, credentialKey: 'fixture-key', ceilingMicrousd: 1_000_000, ceilingDigest: digest, termsDigest: 'fixture-terms' }, now);
    const samLogin = await fetch(base + '/login', { method: 'POST', body: new URLSearchParams({ name: 'sam', token: 'fixture-sam' }), redirect: 'manual' });
    const samCookie = samLogin.headers.get('set-cookie')!.split(';')[0]!;
    const samTerms = (await (await fetch(base + '/api/team?conversation=' + state.selected.id, { headers: { cookie: samCookie } })).json()).snapshot.chatAuthorization;
    const enabled = await (await fetch(base + '/api/team', { method: 'POST', headers: { authorization: 'Bearer sam:fixture-sam', 'content-type': 'application/json' }, body: JSON.stringify({ operation: 'authorize', args: { conversationId: state.selected.id, termsDigest: samTerms.termsDigest, ceilingUsd: samTerms.conversationCeilingUsd } }) })).json();
    expect(enabled.ok).toBe(true);
    const review = await (await fetch(base + '/chat?conversation=' + state.selected.id + '&proposal=' + proposal + '&format=workspace', { headers: { cookie: samCookie } })).json();
    expect(review.pageHtml).toContain('Wait for the settings copy decision.');
    expect((await fetch(base + '/chat?private=1', { headers: { cookie: samCookie } })).status).toBe(403);
    expect(review.pageHtml).toContain('/chat/proposal/' + proposal + '/confirm');
    const confirmed = await fetch(base + '/chat/proposal/' + proposal + '/confirm', { method: 'POST', headers: { cookie: samCookie }, body: new URLSearchParams({ csrf: review.csrf, return: '/chat?conversation=' + state.selected.id }), redirect: 'manual' });
    expect(confirmed.status).toBe(303);
    expect(store.getMateProposal(proposal)?.state).toBe('confirmed');
    expect(store.getMateProposal(proposal)?.resolvedBy).toBe('sam');
    expect(store.activeHolds(store.lookupRef('shared-task')!.id, now)).toHaveLength(1);
    const refused = await fetch(base + '/chat/proposal/' + nativeOnly + '/confirm', { method: 'POST', headers: { cookie: samCookie }, body: new URLSearchParams({ csrf: review.csrf, return: '/chat?conversation=' + state.selected.id }), redirect: 'manual' });
    expect(refused.status).toBe(303);
    const location = refused.headers.get('location')!;
    expect(location).toContain('conversation=' + state.selected.id); expect(location).toContain('said=');
    const refusalPage = await (await fetch(base + location + '&format=workspace', { headers: { cookie: samCookie } })).json();
    expect(refusalPage.notices.join(' ')).toContain('open the task');
    expect(store.getMateProposal(nativeOnly)?.state).toBe('pending');


  });
});
